In [1]:
import pandas as pd

In [35]:
Gpcrs = ['Ccr1',
 'Ccr2',
 'Ccr3',
 'Ccr4',
 'Ccr5',
 'Ccr8',
 'Ccrl2',
 'Cx3cr1',
 'Xcr1',
 'Gpr137',
 'Ccr6',
 'Ccr7',
 'Ccr9',
 'Ccr10',
 'Ackr4',
 'Cxcr1',
 'Cxcr2',
 'Cxcr3',
 'Cxcr4',
 'Cxcr5',
 'Cxcr6',
 'Ackr3',
 'Ackr1',
 'Gper1',
 'Gpr182',
 'Agtr1a',
 'Agtr2',
 'Aplnr',
 'Bdkrb1',
 'Bdkrb2',
 'Gpr15',
 'Gpr25',
 'Npbwr1',
 'Npbwr2',
 'Oprd1',
 'Oprk1',
 'Oprm1',
 'Oprl1',
 'Sstr1',
 'Sstr2',
 'Sstr3',
 'Sstr4',
 'Sstr5',
 'Gpr1',
 'Cysltr1',
 'Cysltr2',
 'Galr1',
 'Galr2',
 'Galr3',
 'Kiss1r',
 'Ltb4r2',
 'Ltb4r1',
 'Oxer1',
 'Mchr1',
 'Mchr2',
 'Rxfp1',
 'Rxfp2',
 'Rxfp3',
 'Rxfp4',
 'Uts2r',
 'Cckar',
 'Cckbr',
 'Gnrhr',
 'Npffr1',
 'Npffr2',
 'Hcrtr1',
 'Hcrtr2',
 'Qrfpr',
 'Avpr1a',
 'Avpr1b',
 'Avpr2',
 'Oxtr',
 'Gpr22',
 'Gpr176',
 'Brs3',
 'Grpr',
 'Nmbr',
 'Ednra',
 'Ednrb',
 'Ghsr',
 'Mlnr',
 'Nmur1',
 'Nmur2',
 'Npsr1',
 'Ntsr1',
 'Ntsr2',
 'Trhr',
 'Gpr37',
 'Gpr39',
 'C3ar1',
 'C5ar1',
 'Cmkrl1',
 'Fpr1',
 'Fpr2',
 'Fpr3',
 'Gpbar1',
 'Gpr32',
 'Ptgdr2',
 'C5ar2',
 'Mas1',
 'Mas1l',
 'Mrgprd',
 'Mrgpre',
 'Mrgprf',
 'Mrgprg',
 'Mrgprx1',
 'Mrgprx2',
 'Mrgprx3',
 'Mrgprx4',
 'Mtnr1a',
 'Mtnr1b',
 'Npy1r',
 'Npy2r',
 'Npy5r',
 'Ppy1r',
 'Prokr1',
 'Prokr2',
 'Prlhr',
 'Tacr1',
 'Tacr2',
 'Tacr3',
 'Gpr19',
 'Gpr50',
 'Gpr75',
 'Gpr83',
 'Fshr',
 'Lhcgr',
 'Tshr',
 'Lgr4',
 'Lgr5',
 'Lgr6',
 'Ffar1',
 'Ffar2',
 'Ffar3',
 'Ffar4',
 'Hcar1',
 'Hcar2',
 'Hcar3',
 'Oxgr1',
 'P2ry1',
 'P2ry2',
 'P2ry4',
 'P2ry6',
 'P2ry8',
 'P2ry11',
 'Sucnr1',
 'Gpr31',
 'Gpr82',
 'P2ry12',
 'P2ry13',
 'P2ry14',
 'Ptafr',
 'Gpr34',
 'Gpr87',
 'Gpr171',
 'Cnr1',
 'Cnr2',
 'Lpar1',
 'Lpar2',
 'Lpar3',
 'Mc1r',
 'Mc2r',
 'Mc3r',
 'Mc4r',
 'Mc5r',
 'S1pr1',
 'S1pr2',
 'S1pr3',
 'S1pr4',
 'S1pr5',
 'Gpr3',
 'Gpr6',
 'Gpr12',
 'Ptgdr',
 'Ptgdr2',
 'Ptger1',
 'Ptger2',
 'Ptger3',
 'Ptger4',
 'Ptgfr',
 'Ptgir',
 'Tbxa2r',
 'Lpar4',
 'Lpar5',
 'Lpar6',
 'P2ry10',
 'F2r',
 'F2rl1',
 'F2rl2',
 'F2rl3',
 'Gpr4',
 'Gpr17',
 'Gpr18',
 'Gpr20',
 'Gpr35',
 'Gpr55',
 'Gpr65',
 'Gpr132',
 'Gpr183',
 'Opn3',
 'Opn5',
 'Htr2a',
 'Htr2b',
 'Htr2c',
 'Htr6',
 'Adra1a',
 'Adra1b',
 'Adra1d',
 'Adra2a',
 'Adra2b',
 'Adra2c',
 'Adrb1',
 'Adrb2',
 'Adrb3',
 'Drd1',
 'Drd2',
 'Drd3',
 'Drd4',
 'Drd5',
 'Hrh2',
 'Taar1',
 'Taar2',
 'Taar5',
 'Taar6',
 'Taar8',
 'Taar9',
 'Adora1',
 'Adora2a',
 'Adora2b',
 'Adora3',
 'Hrh1',
 'Hrh3',
 'Hrh4',
 'Chrm1',
 'Chrm2',
 'Chrm3',
 'Chrm4',
 'Chrm5',
 'Gpr21',
 'Gpr27',
 'Gpr45',
 'Gpr52',
 'Gpr61',
 'Gpr62',
 'Gpr63',
 'Gpr78',
 'Gpr84',
 'Gpr85',
 'Gpr88',
 'Gpr101',
 'Gpr161',
 'Gpr173',
 'Htr1a',
 'Htr1b',
 'Htr1d',
 'Htr1e',
 'Htr1f',
 'Htr4',
 'Htr5a',
 'Htr7',
 'Tas2r1',
 'Tas2r3',
 'Tas2r4',
 'Tas2r5',
 'Tas2r7',
 'Tas2r8',
 'Tas2r9',
 'Tas2r10',
 'Tas2r13',
 'Tas2r14',
 'Tas2r16',
 'Tas2r19',
 'Tas2r20',
 'Tas2r31',
 'Tas2r38',
 'Tas2r39',
 'Tas2r40',
 'Tas2r41',
 'Tas2r42',
 'Tas2r43',
 'Tas2r45',
 'Tas2r46',
 'Tas2r50',
 'Tas2r60',
 'Gpr26',
 'Gpr68',
 'Gpr119',
 'Gpr135',
 'Gpr139',
 'Gpr141',
 'Gpr142',
 'Gpr143',
 'Gpr146',
 'Gpr148',
 'Gpr149',
 'Gpr150',
 'Gpr151',
 'Gpr152',
 'Gpr153',
 'Gpr157',
 'Gpr160',
 'Gpr162',
 'Gpr174',
 'Adgrb1',
 'Adgrb2',
 'Adgrb3',
 'Adgre5',
 'Adgrc1',
 'Adgrc2',
 'Adgrc3',
 'Adgrl4',
 'Adgre1',
 'Adgre2',
 'Adgre3',
 'Adgrg1',
 'Adgrg2',
 'Adgrg3',
 'Adgrv1',
 'Adgrf1',
 'Adgrf2',
 'Adgrg4',
 'Adgrf3',
 'Adgrg5',
 'Adgrf4',
 'Adgrf5',
 'Adgre4',
 'Adgra1',
 'Adgra2',
 'Adgra3',
 'Adgrg6',
 'Adgrg7',
 'Adgrd1',
 'Adgrd2',
 'Gpr157',
 'Adgrl1',
 'Adgrl2',
 'Adgrl3',
 'Fzd1',
 'Fzd2',
 'Fzd3',
 'Fzd4',
 'Fzd5',
 'Fzd6',
 'Fzd7',
 'Fzd8',
 'Fzd9',
 'Fzd10',
 'Smo',
 'Casr',
 'Gprc6a',
 'Gabbr1',
 'Gabbr2',
 'Grm1',
 'Grm2',
 'Grm3',
 'Grm4',
 'Grm5',
 'Grm6',
 'Grm7',
 'Grm8',
 'Tas1r1',
 'Tas1r2',
 'Tas1r3',
 'Gpr156',
 'Gpr158',
 'Gpr179',
 'Gprc5a',
 'Gprc5b',
 'Gprc5c',
 'Gprc5d',
 'Calcrl',
 'Calcr',
 'Crhr1',
 'Crhr2',
 'Gcgr',
 'Ghrhr',
 'Glp1r',
 'Gipr',
 'Glp2r',
 'Sctr',
 'Pth1r',
 'Pth2r',
 'Adcyap1r1',
 'Vipr1',
 'Vipr2']

In [36]:
Gpcrs = list(set(Gpcrs))

In [61]:
df_de = pd.read_excel(r"E:\KCL\scRNAseq\scRNAseq\mouse\GSM6160615_adata\phd thesis\de_endo_cell_type.xlsx", sheet_name="Sheet1", index_col=0)

In [62]:
df_de

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Xkr4,15.398510,0.012707,0.466770,0.027223,9.782820e-01,9.918068e-01
Mrpl15,408.445630,-0.271716,0.086129,-3.154745,1.606382e-03,8.015803e-03
Lypla1,486.592329,0.120782,0.080938,1.492282,1.356252e-01,3.084667e-01
Tcea1,730.970760,0.016040,0.064640,0.248145,8.040221e-01,9.102600e-01
Rgs20,8.884463,-0.070140,0.569435,-0.123174,9.019692e-01,9.586329e-01
...,...,...,...,...,...,...
Tmlhe,2.149921,0.137201,1.168031,0.117464,9.064926e-01,NaN
AC168977.1,2.287101,-0.050464,1.143607,-0.044127,9.648029e-01,NaN
PISD,1320.693525,0.374264,0.050900,7.352967,1.938545e-13,3.132715e-12
DHRSX,361.150189,-0.550866,0.096424,-5.712931,1.110466e-08,1.229865e-07
CAAA01147332.1,5.592560,0.025274,0.739493,0.034177,9.727357e-01,9.898144e-01

In [63]:
df_de_gpcrs = df_de.loc[df_de.index.isin(Gpcrs)]

In [64]:
df_de_gpcrs

          baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
Adgrb3  141.167283        0.286499  0.145614  1.967524  0.049123  0.144613
Gpr45   697.807629        0.112635  0.067180  1.676611  0.093619  0.235820
Fzd7     49.263915        0.312839  0.253489  1.234133  0.217153  0.425606
Gpr1      3.044267       -0.757793  1.003162 -0.755405  0.450006  0.673371
Fzd5     38.435676       -0.085317  0.276985 -0.308022  0.758066  0.885228
...            ...             ...       ...       ...       ...       ...
Galr1    92.391660       -0.048504  0.181399 -0.267388  0.789171  0.902054
Gpr137  294.522538        0.048473  0.100520  0.482219  0.629650  0.807711
Ffar4   216.593183       -0.191595  0.125216 -1.530118  0.125988  0.291863
Adra2a  562.373962        0.306402  0.073745  4.154874  0.000033  0.000232
Adrb1    16.391719       -0.844348  0.460038 -1.835389  0.066448  0.183208

[133 rows x 6 columns]

In [65]:
df_de_not_gpcrs = df_de.loc[~df_de.index.isin(Gpcrs)]

In [66]:
df_de_not_gpcrs

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Xkr4,15.398510,0.012707,0.466770,0.027223,9.782820e-01,9.918068e-01
Mrpl15,408.445630,-0.271716,0.086129,-3.154745,1.606382e-03,8.015803e-03
Lypla1,486.592329,0.120782,0.080938,1.492282,1.356252e-01,3.084667e-01
Tcea1,730.970760,0.016040,0.064640,0.248145,8.040221e-01,9.102600e-01
Rgs20,8.884463,-0.070140,0.569435,-0.123174,9.019692e-01,9.586329e-01
...,...,...,...,...,...,...
Tmlhe,2.149921,0.137201,1.168031,0.117464,9.064926e-01,NaN
AC168977.1,2.287101,-0.050464,1.143607,-0.044127,9.648029e-01,NaN
PISD,1320.693525,0.374264,0.050900,7.352967,1.938545e-13,3.132715e-12
DHRSX,361.150189,-0.550866,0.096424,-5.712931,1.110466e-08,1.229865e-07
CAAA01147332.1,5.592560,0.025274,0.739493,0.034177,9.727357e-01,9.898144e-01

In [67]:
df_de_gpcrs.to_excel('df_de_endo_gpcrs.xlsx', sheet_name='de_endo_gpcrs')

In [68]:
df_de_not_gpcrs.to_excel('df_de_endo_not_gpcrs.xlsx', sheet_name='de_endo_not_gpcrs')